export const courierLibraries = [
  "Adams Public Library",
  "Agness Community Library",
  "Alliance Central Staff",
  "Aloha Community Library",
  "Amity Public Library",
  "Arlington Public Library",
  "Asotin County Library",
  "Astoria Public Library",
  "Athena Public Library",
  "Athol Branch",
  "Baker County Library",
  "Bandon Public Library",
  "Banks Public Library",
  "Beaverton City Library",
  "Bellingham Public Library",
  "Blue Mountain Community College",
  "Burns High School",
  "Bushnell Univ",
  "Canby Public Library",
  "Cascade Locks Library",
  "Cedar Mill Library",
  "Central Oregon Community College",
  "Central Washington Univ",
  "Chemeketa Community College",
  "Chemeketa Cooperative Regional Library Service",
  "Chetco Community Public Library",
  "Christmas Valley Branch",
  "Clackamas Community College",
  "Clackamas County Library - Gladstone Public Library",
  "Clackamas County Library - Oak Lodge Branch",
  "Clark College",
  "Clatsop Community College",
  "Coeur d'Alene Public Library",
  "Columbia Gorge Community College - Hood River Campus",
  "Columbia Gorge Community College - Main Campus",
  "Confederate Tribes of Grand Ronde Tribal Library",
  "Coos Bay Public Library",
  "Coos County Library Services",
  "Coquille Public Library",
  "Corban Univ",
  "Cornelius Public Library",
  "Cove School Library",
  "Crane Union High School",
  "Curry Public Library District",
  "Dallas Public Library",
  "Dayton (Mary Gilkey Public Library)",
  "Deschutes Public Library",
  "Deschutes Public Library - East Bend",
  "Deschutes Public Library - La Pine Branch",
  "Deschutes Public Library - Redmond Branch",
  "Deschutes Public Library - Sisters Branch",
  "Deschutes Public Library - Sunriver Branch",
  "Dora Public Library",
  "Driftwood Public Library",
  "Dufur School/Community Library",
  "Eastern Oregon Univ",
  "Eastern Washington Univ",
  "Echo Public Library",
  "Elgin High School",
  "Elgin Public Library",
  "Ellensburg Public Library",
  "Enterprise Public Library",
  "Estacada Public Library",
  "Forest Grove City Library",
  "Fort Vancouver Regional Library",
  "Fossil City Library",
  "Garden Home Community Library",
  "George Fox Univ - Newberg",
  "Gilliam County Library",
  "Gladstone Public Library",
  "Gonzaga Univ",
  "Gonzaga Univ School of Law",
  "Grant County Library",
  "Haines Branch Library",
  "Halfway Branch Library",
  "Happy Valley Public Library",
  "Harney County Library",
  "Harney ESD Resource Center",
  "Harrison Branch Library",
  "Hayden Library",
  "Helix Public Library",
  "Hermiston High School Library",
  "Hermiston Public Library",
  "Hillsboro Brookwood Library",
  "Hines Middle School",
  "Hood River County Library District",
  "Hood River Valley High School",
  "Hoodland Public Library",
  "Huntington Branch Library",
  "Huntington School Library",
  "Independence Public Library",
  "Intermountain ESD",
  "Ione High School Library",
  "Ione Public Library",
  "Jackson County Library Services",
  "Jefferson Public Library",
  "Joseph Public Library",
  "King County Library System",
  "Kitsap Regional Library",
  "Klamath Community College Library",
  "Klamath County Library",
  "La Grande Public Library",
  "Lake County Library",
  "Lake Oswego Public Library",
  "Lakeside Public Library",
  "Lane Community College",
  "Langlois Public Library",
  "Latah County Library",
  "Ledding Library of Milwaukie",
  "Lewis & Clark - Northwestern School of Law",
  "Lewis & Clark College",
  "Lewis-Clark State College",
  "Lewiston City Library",
  "LINCC",
  "Lincoln County Library District",
  "Linfield Univ - McMinnville",
  "Linfield Univ - Portland",
  "Lyons Public Library",
  "McLoughlin High School Library",
  "McMinnville Public Library",
  "Milton-Freewater Public Library",
  "Mobile Branch Library",
  "Molalla Public Library",
  "Monmouth Public Library",
  "Mount Angel Abbey",
  "Mt. Angel Public Library",
  "Mt. Hood Community College",
  "Multnomah County Library",
  "Multnomah Univ",
  "Myrtle Point Public Library",
  "Newberg Public Library",
  "Newport Public Library",
  "North Bend Public Library",
  "North Central Washington Libraries",
  "North Idaho College",
  "North Plains Public Library",
  "North Powder Public Library",
  "Nyssa Public Library",
  "Ontario Community Library",
  "Ontario High School",
  "Ontario Middle School",
  "Oregon City Public Library",
  "Oregon Coast Community College",
  "Oregon Health & Science Univ",
  "Oregon Institute of Technology - Klamath Falls",
  "Oregon Institute of Technology - Wilsonville",
  "Oregon National Primate Research Center",
  "Oregon State Univ - Cascades",
  "Oregon State Univ - Corvallis",
  "Oregon State Univ/Hatfield Marine Science",
  "Oregon Trail Library District - Boardman Branch",
  "Oregon Trail Library District - Heppner Branch",
  "Oregon Trail Library District - Irrigon Branch",
  "Osburn Public Library",
  "Pacific Lutheran Univ",
  "Pacific Univ - Forest Grove",
  "Pacific Univ - Hillsboro",
  "Paisley Branch Library",
  "Parkdale Library",
  "Pendleton High School Library",
  "Pendleton Public Library",
  "Pierce County Library System",
  "Pilot Rock Public Library",
  "Pinehurst Branch Library",
  "Plummer Public Library",
  "Port Orford Public Library",
  "Portland Community College",
  "Portland State Univ",
  "Post Falls",
  "Powers Public Library",
  "Rathdrum Branch Library",
  "Reed College",
  "Richland Branch Library [Oregon]",
  "Rogue Community College - Redwood Campus",
  "Rogue Community College - Riverside Campus",
  "Rogue Community College - Table Rock Campus",
  "Saint Martin's Univ",
  "Salem Public Library",
  "Sandy Public Library",
  "Seaside Public Library",
  "Seattle Pacific Univ",
  "Seattle Public Library",
  "Seattle Univ",
  "Seattle Univ - School of Law",
  "Sheridan Public Library",
  "Sherman County Public/School Library",
  "Sherwood Public Library",
  "Siletz Public Library",
  "Silver Falls Library District",
  "Silver Hills Elementary School Library",
  "Silver Lake Branch Library",
  "Slater Elementary",
  "Sno-Isle Libraries",
  "Southern Oregon Univ - Ashland",
  "Southern Oregon Univ - Medford/Rogue CC",
  "Southern Wasco County Library",
  "Southwestern Oregon Community College",
  "Spirit Lake Branch Library",
  "Spokane County Library District",
  "Spokane Public Library",
  "St. Maries Public Library",
  "Stanfield Public Library",
  "Stanfield Secondary School Library",
  "State Library of Oregon",
  "Stayton Public Library",
  "Sumpter Branch Library",
  "Tacoma Public Library",
  "The Dalles-Wasco County Library",
  "The Evergreen State College",
  "Tigard Public Library",
  "Tillamook Bay Community College",
  "Tillamook County Library",
  "Timberland Regional Library",
  "Toledo Public Library",
  "Treasure Valley Community College",
  "Tualatin Public Library",
  "Ukiah Public Library",
  "Umatilla Public Library",
  "Union Carnegie Public Library",
  "Univ of Idaho",
  "Univ of Idaho Law Library",
  "Univ of Oregon - Eugene",
  "Univ of Oregon - Portland",
  "Univ of Portland",
  "Univ of Puget Sound",
  "Univ of Washington",
  "Univ of Washington - Bothell",
  "Univ of Washington - Law",
  "Univ of Washington - Tacoma",
  "Vale Emma Humphrey Public Library",
  "Vale Union High School Library",
  "Waldport Public Library",
  "Walla Walla County Rural Library District",
  "Walla Walla Univ",
  "Walla Walla Univ - School of Nursing",
  "Wallace High School Library",
  "Wallace Public Library",
  "Wallowa Public Library",
  "Warner Pacific Univ",
  "Warrenton Community Library",
  "Washington State Library",
  "Washington State Univ  - Tri-Cities, Richland",
  "Washington State Univ  - Vancouver",
  "Washington State Univ - Pullman",
  "Washington State Univ - Spokane",
  "WCCLS",
  "WCCLS Central Office",
  "West Linn Public Library",
  "West Salem Branch Library",
  "West Slope Community Library",
  "Western Oregon Univ",
  "Western Seminary",
  "Western Washington Univ",
  "Weston Public Library",
  "Whatcom County Library System",
  "Whitman College",
  "Whitworth Univ",
  "Willamette Univ",
  "Willamette Univ - Pacific Northwest College of Art",
  "Willamette Univ College of Law",
  "Willamina Public Library",
  "Wilsonville Public Library",
  "Woodburn Public Library",
];
